version: '3'

services:
  app:
    image: walt3rl/ttrss:${TAG:-dev}
    build:
      context: .
    ports:
      - ${LOCAL_PORT}:80
    depends_on:
      - db
    links:
      - db
    environment:
      - TTRSS_DB_HOST=db
      - TTRSS_DB_NAME=${TTRSS_DB_NAME:-ttrss}
      - TTRSS_DB_USER=${TTRSS_DB_USER:-postgres}
      - TTRSS_DB_PASS=${TTRSS_DB_PASS:-hunter2}
      - TTRSS_SELF_URL_PATH=http://127.0.0.1:${LOCAL_PORT}
    restart: unless-stopped
    volumes:
      - ./backups:/backups
      - ./config.d:/opt/tt-rss/config.d:ro

  db:
    image: postgres:12
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ${TTRSS_DB_PASS}
      POSTGRES_USER: ${TTRSS_DB_USER}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
